name: pipewire
base: core24
adopt-info: pipewire
summary: Pipewire server, plus wireplumber and pipewire-pulse
description: |
  The pipewire video/audio daemon server.

grade: stable
confinement: strict

layout:
  /usr/share/pipewire:
    bind: $SNAP/usr/share/pipewire
  /usr/share/wireplumber:
    bind: $SNAP/usr/share/wireplumber
  /usr/bin/wireplumber:
    symlink: $SNAP/usr/bin/wireplumber
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /usr/share/alsa-card-profile:
    bind: $SNAP/usr/share/alsa-card-profile
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pipewire-0.3:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pipewire-0.3
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/wireplumber-0.5:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/wireplumber-0.5
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib
  /etc/alsa:
    bind: $SNAP/etc/alsa
  /etc/pulse:
    bind: $SNAP/etc/pulse

environment:
  SPA_PLUGIN_DIR: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/spa-0.2
  LD_LIBRARY_PATH: ${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}/usr/lib:/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pipewire-0.3:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio

apps:
  pipewire-bin:
    command: usr/bin/pipewire
    daemon: simple
    # it's socket-activated, so if it dies/is killed, don't relaunch it
    restart-condition: never
    sockets:
      pipewire-socket:
        listen-stream: $XDG_RUNTIME_DIR/pipewire-0
        socket-mode: 0644
      pipewire-manager-socket:
        listen-stream: $XDG_RUNTIME_DIR/pipewire-0-manager
        socket-mode: 0644
    passthrough:
      daemon-scope: user
    slots: &pwslots
      - pipewire
      - audio-playback
      - audio-record
      - pulseaudio
      - dbus-wireplumber
      - dbus-pulseaudio
      - dbus-freedesktop-reservedevice1-audio0
      - dbus-freedesktop-reservedevice1-audio1
      - dbus-freedesktop-reservedevice1-audio2
      - dbus-freedesktop-reservedevice1-audio3
      - dbus-freedesktop-reservedevice1-audio4
      - dbus-freedesktop-reservedevice1-audio5
      - dbus-freedesktop-reservedevice1-audio6
      - dbus-freedesktop-reservedevice1-audio7
      - dbus-freedesktop-reservedevice1-audio8
      - dbus-freedesktop-reservedevice1-audio9
    plugs: &pwplugs
      - alsa
      - bluez
      - camera
      - hardware-observe
      - media-control
      - network
      - network-bind
      - system-observe

  pipewire-pulse:
    command: usr/bin/pipewire-pulse
    daemon: simple
    restart-condition: never
    passthrough:
      daemon-scope: user
    sockets:
      pulse-socket:
        listen-stream: $XDG_RUNTIME_DIR/pulse/native
        socket-mode: 0644
    slots: *pwslots
    plugs: *pwplugs

# apps for server-wide daemon
  pipewire-server-bin:
    command: usr/bin/pipewire
    daemon: simple
    restart-condition: never
    sockets:
      pipewire-socket:
        listen-stream: $SNAP_COMMON/pipewire-0
        socket-mode: 0644
    slots: *pwslots
    plugs: *pwplugs
    environment: &serverenviron
      PIPEWIRE_RUNTIME_DIR: $SNAP_COMMON
      PULSE_SERVER: $SNAP_COMMON

  pipewire-server-pulse:
    command: usr/bin/pipewire-pulse
    daemon: simple
    restart-condition: never
    sockets:
      pulse-socket:
        listen-stream: $SNAP_COMMON/pulse/native
        socket-mode: 0644
    slots: *pwslots
    plugs: *pwplugs
    environment: *serverenviron

  pw-play:
    command: usr/bin/pw-play
    slots: &pwtoolsslots
      - pipewire
      - audio-playback

  pw-cat:
    command: usr/bin/pw-cat
    slots: *pwtoolsslots

  pw-cli:
    command: usr/bin/pw-cli
    slots: *pwtoolsslots

  pw-config:
    command: usr/bin/pw-config
    slots: *pwtoolsslots

  pw-dot:
    command: usr/bin/pw-dot
    slots: *pwtoolsslots

  pw-dsdplay:
    command: usr/bin/pw-dsdplay
    slots: *pwtoolsslots

  pw-dump:
    command: usr/bin/pw-dump
    slots: *pwtoolsslots

  pw-encplay:
    command: usr/bin/pw-encplay
    slots: *pwtoolsslots

  pw-link:
    command: usr/bin/pw-link
    slots: *pwtoolsslots

  pw-loopback:
    command: usr/bin/pw-loopback
    slots: *pwtoolsslots

  pw-metadata:
    command: usr/bin/pw-metadata
    slots: *pwtoolsslots

  pw-mididump:
    command: usr/bin/pw-mididump
    slots: *pwtoolsslots

  pw-midiplay:
    command: usr/bin/pw-midiplay
    slots: *pwtoolsslots

  pw-midirecord:
    command: usr/bin/pw-midirecord
    slots: *pwtoolsslots

  pw-mon:
    command: usr/bin/pw-mon
    slots: *pwtoolsslots

  pw-profiler:
    command: usr/bin/pw-profiler
    slots: *pwtoolsslots

  pw-record:
    command: usr/bin/pw-record
    slots: *pwtoolsslots

  pw-top:
    command: usr/bin/pw-top
    slots: *pwtoolsslots

slots:
  dbus-wireplumber:
    interface: dbus
    name: org.freedesktop.ReserveDevice1
    bus: session
  dbus-pulseaudio:
    interface: dbus
    name: org.pulseaudio.Server
    bus: session
  dbus-freedesktop-reservedevice1-audio0:
    interface: dbus
    bus: session
    name: org.freedesktop.ReserveDevice1.Audio0
  dbus-freedesktop-reservedevice1-audio1:
    interface: dbus
    bus: session
    name: org.freedesktop.ReserveDevice1.Audio1
  dbus-freedesktop-reservedevice1-audio2:
    interface: dbus
    bus: session
    name: org.freedesktop.ReserveDevice1.Audio2
  dbus-freedesktop-reservedevice1-audio3:
    interface: dbus
    bus: session
    name: org.freedesktop.ReserveDevice1.Audio3
  dbus-freedesktop-reservedevice1-audio4:
    interface: dbus
    bus: session
    name: org.freedesktop.ReserveDevice1.Audio4
  dbus-freedesktop-reservedevice1-audio5:
    interface: dbus
    bus: session
    name: org.freedesktop.ReserveDevice1.Audio5
  dbus-freedesktop-reservedevice1-audio6:
    interface: dbus
    bus: session
    name: org.freedesktop.ReserveDevice1.Audio6
  dbus-freedesktop-reservedevice1-audio7:
    interface: dbus
    bus: session
    name: org.freedesktop.ReserveDevice1.Audio7
  dbus-freedesktop-reservedevice1-audio8:
    interface: dbus
    bus: session
    name: org.freedesktop.ReserveDevice1.Audio8
  dbus-freedesktop-reservedevice1-audio9:
    interface: dbus
    bus: session
    name: org.freedesktop.ReserveDevice1.Audio9


parts:
  pipewire:
    plugin: meson
    source: https://git.launchpad.net/ubuntu/+source/pipewire
    source-branch: 'applied/ubuntu/oracular'
    source-type: git
    meson-parameters:
      - --prefix=/usr
      - -Doptimization=3
      - -Ddebug=true
      - -Dexamples=disabled
      - -Dman=disabled
      - -Dtests=disabled
      - -Dsystemd=enabled
      - -Dsnap=enabled
      - -Dsystemd-user-service=enabled
      - -Dsystemd-system-service=enabled
    override-pull: |
      craftctl default
      git_ver="$(git describe --tags --match "applied/*")"
      git_ver="${git_ver#importer/}"
      git_ver="${git_ver#applied/}"
      git_ver="${git_ver%-0-g*}"
      craftctl set version="${git_ver}"
      patch -p1 < $CRAFT_PROJECT_DIR/patches/launch-wireplumber.diff
    build-packages:
      - dpkg-dev
      - debhelper-compat
      - graphviz
      - libapparmor-dev
      - libasound2-dev
      - libavahi-client-dev
      - libbluetooth-dev
      - libcamera-dev
      - libdbus-1-dev
      - libffado-dev
      - libfreeaptx-dev
      - libglib2.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-dev
      - libjack-jackd2-dev
      - libcanberra-dev
      - liblc3-dev
      - libldacbt-abr-dev
      - libldacbt-enc-dev
      - liblilv-dev
      - libmysofa-dev
      - libncurses-dev
      - libopus-dev
      - libpulse-dev
      - libreadline-dev
      - libroc-dev
      - libsbc-dev
      - libsdl2-dev
      - libsnapd-glib-dev
      - libsndfile1-dev
      - libssl-dev
      - libsystemd-dev
      - libudev-dev
      - libusb-1.0-0-dev
      - libv4l-dev
      - libwebrtc-audio-processing-dev
      - libxfixes-dev
      - meson
      - modemmanager-dev
      - pkgconf
      - python3-docutils
      - systemd-dev
    stage-packages:
      - libxfixes3
      - libcanberra0t64
      - libroc0.3
      - libvorbisfile3
      - libpulse0
      - libffado2
      - liblilv-0-0
      - libavahi-client3
      - libopusenc0
      - libopus0
      - libudev1
      - libsnapd-glib-2-1
      - libbluetooth3
      - libjson-glib-1.0-0
      - libnghttp2-14
      - libpsl5t64
      - libsoup-3.0-0
      - libwebrtc-audio-processing1
      - libasound2t64
      - libgstreamer-plugins-base1.0-0
      - libmysofa1
      - libcamera0.2
      - libldacbt-enc2
      - libsbc1
      - liblc3-1
      - libldacbt-abr2
      - libfreeaptx0
      - libfdk-aac2
      - libflac12t64
      - libmp3lame0
      - libmpg123-0t64
      - libogg0
      - libsndfile1
      - libvorbisenc2
      - libvorbis0a
      - libusb-1.0-0
      - psmisc
      - bluez-alsa-utils
      - yaru-theme-sound
      - pulseaudio-utils
      - alsa-utils

    stage:
      - -usr/bin/meson
      - -usr/bin/ninja
      - -usr/lib/python3
      - -etc/pulse/client.conf.d/01-enable-autospawn.conf
      - -usr/share/doc
      - -usr/share/pkgconfig
      - -usr/share/upstart
      - -usr/share/man
      - -usr/share/session-migration
      - -usr/include
