name: pipewire
base: core24
version: '1.2.3'
summary: Pipewire server, plus wireplumber and pipewire-pulse
description: |
  The pipewire video/audio daemon server.

grade: stable
confinement: strict

layout:
  /usr/share/pipewire:
    bind: $SNAP/usr/share/pipewire
  /usr/share/wireplumber:
    bind: $SNAP/usr/share/wireplumber
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /usr/share/alsa-card-profile:
    bind: $SNAP/usr/share/alsa-card-profile
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pipewire-0.3:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pipewire-0.3
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/wireplumber-0.4:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/wireplumber-0.4

environment:
  SPA_PLUGIN_DIR: $SNAP/usr/lib/x86_64-linux-gnu/spa-0.2
  PIPEWIRE_RUNTIME_DIR: $XDG_RUNTIME_DIR/..
  PULSE_RUNTIME_PATH: $XDG_RUNTIME_DIR/../pulse

apps:
  pipewire:
    command: snap/command-chain/pipewire
    daemon: simple
    passthrough:
      daemon-scope: user
    plugs:
      - alsa
      - audio-playback
      - audio-record
      - bluez
      - hardware-observe
      - network
      - network-bind
      - snapd-control
      - system-observe

slots:
  dbus-portal:
    interface: dbus
    name: org.freedesktop.impl.portal.PermissionStore
    bus: session
  dbus-wireplumber:
    interface: dbus
    name: org.freedesktop.ReserveDevice1
    bus: session
  dbus-pulseaudio:
    interface: dbus
    name: org.pulseaudio.Server
    bus: session

parts:
  pipewire:
    plugin: meson
    source: https://git.launchpad.net/ubuntu/+source/pipewire
    source-branch: 'applied/ubuntu/noble-updates'
    source-type: git
    meson-parameters:
      - --prefix=/usr
      - -Doptimization=3
      - -Ddebug=true
      - -Dexamples=disabled
      - -Dman=disabled
      - -Dtests=disabled
      - -Dsystemd=enabled
      - -Dsnap=enabled
#      - -Dsession-managers=[]
      - -Dsnap=enabled
    build-packages:
      - dpkg-dev
      - debhelper-compat
      - graphviz
      - libapparmor-dev
      - libasound2-dev
      - libavahi-client-dev
      - libbluetooth-dev
      - libcamera-dev
      - libdbus-1-dev
      - libffado-dev
      - libfreeaptx-dev
      - libglib2.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-dev
      - libjack-jackd2-dev
      - libcanberra-dev
      - liblc3-dev
      - libldacbt-abr-dev
      - libldacbt-enc-dev
      - liblilv-dev
      - libmysofa-dev
      - libncurses-dev
      - libopus-dev
      - libpulse-dev
      - libreadline-dev
      - libroc-dev
      - libsbc-dev
      - libsdl2-dev
      - libsnapd-glib-dev
      - libsndfile1-dev
      - libssl-dev
      - libsystemd-dev
      - libudev-dev
      - libusb-1.0-0-dev
      - libv4l-dev
      - libwebrtc-audio-processing-dev
      - libxfixes-dev
      - meson
      - modemmanager-dev
      - pkgconf
      - python3-docutils
      - systemd-dev
    stage-packages:
      - libxfixes3
      - libcanberra0t64
      - libroc0.3
      - libvorbisfile3
      - libpulse0
      - libffado2
      - liblilv-0-0
      - libavahi-client3
      - libopusenc0
      - libopus0
      - libudev1
      - libsnapd-glib-2-1
      - libbluetooth3
      - libjson-glib-1.0-0
      - libnghttp2-14
      - libpsl5t64
      - libsoup-3.0-0
      - libwebrtc-audio-processing1
      - libasound2t64
      - libgstreamer-plugins-base1.0-0
      - libmysofa1
      - libcamera0.2
      - libldacbt-enc2
      - libsbc1
      - liblc3-1
      - libldacbt-abr2
      - libfreeaptx0
      - libfdk-aac2
      - libflac12t64
      - libmp3lame0
      - libmpg123-0t64
      - libogg0
      - libsndfile1
      - libvorbisenc2
      - libvorbis0a
      - libusb-1.0-0
    #   - psmisc

  # wireplumber:
  #   plugin: meson
  #   after: [pipewire]
  #   source: https://gitlab.freedesktop.org/pipewire/wireplumber.git
  #   source-tag: '0.5.5'
  #   meson-parameters:
  #     - --prefix=/usr
  #     - -Doptimization=3
  #     - -Ddebug=true
  #     - -Dintrospection=disabled
  #     - -Ddoc=disabled
  #     - -Ddbus-tests=false
  #     - -Dtests=false
  #     - -Dsystemd=enabled

  conditioning:
    plugin: nil
    after: [pipewire]
    override-prime: |
      mkdir -p snap/command-chain
      cp -a $CRAFT_PROJECT_DIR/scripts/* snap/command-chain/
      craftctl default
      rm -f usr/bin/meson
      rm -f usr/bin/ninja
      rm -rf usr/lib/python3
      rm -rf etc/pulse/client.conf.d/01-enable-autospawn.conf
