name: pipewire
base: core22
version: '0.1'
summary: Pipewire server, plus wireplumber and pipewire-pulse
description: |
  The pipewire video/audio daemon server.

grade: devel
confinement: strict

layout:
  /usr/share/pipewire:
    bind: $SNAP/usr/share/pipewire
  /usr/share/wireplumber:
    bind: $SNAP/usr/share/wireplumber
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /usr/share/alsa-card-profile:
    bind: $SNAP/usr/share/alsa-card-profile
  /usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/pipewire-0.3
  /usr/lib/$CRAFT_ARCH_TRIPLET/wireplumber-0.4:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/wireplumber-0.4

environment:
  SPA_PLUGIN_DIR: $SNAP/usr/lib/x86_64-linux-gnu/spa-0.2
  #PIPEWIRE_RUNTIME_DIR: $XDG_RUNTIME_DIR/..
  PULSE_RUNTIME_PATH: $XDG_RUNTIME_DIR/../pulse

apps:
  pipewire:
    command: snap/command-chain/pipewire
    daemon: simple
    passthrough:
      daemon-scope: user

plugs:
  alsa: null
  audio-playback: null
  audio-record: null
  bluez: null
  hardware-observe: null
  network: null
  network-bind: null
  #pipewire-server: null
  snapd-control: null
  system-observe: null

slots:
  dbus-portal:
    interface: dbus
    name: org.freedesktop.impl.portal.PermissionStore
    bus: session
  dbus-wireplumber:
    interface: dbus
    name: org.freedesktop.ReserveDevice1
    bus: session
  dbus-pulseaudio:
    interface: dbus
    name: org.pulseaudio.Server
    bus: session

parts:
  ninja:
    plugin: nil
    source: https://github.com/ninja-build/ninja.git
    source-tag: 'v1.11.1'
    override-build: |
      rm -rf build
      rm -f ninja
      rm -f ninja_bootstrap
      sed -i 's_^#!/usr/bin/env python$_#!/usr/bin/env python3_g' configure.py
      ./configure.py --bootstrap
      mv ninja ninja_bootstrap
      rm -rf build
      ./ninja_bootstrap
      rm -f ninja_bootstrap
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mv ninja $CRAFT_PART_INSTALL/usr/bin/
    build-packages:
      - python3

  meson-deps:
    after: [ ninja ]
    plugin: nil
    source: https://github.com/mesonbuild/meson.git
    source-tag: '1.0.0'
    override-build: |
      python3 -m pip install .
      mkdir -p $CRAFT_PART_INSTALL/usr/lib/python3/dist-packages
      rm -rf $CRAFT_PART_INSTALL/usr/lib/python3/dist-packages/meson*
      python3 -m pip install --target=$CRAFT_PART_INSTALL/usr .
      mv $CRAFT_PART_INSTALL/usr/meson* $CRAFT_PART_INSTALL/usr/lib/python3/dist-packages/
      sed -i "s%^#!/usr/bin/python3$%#!/usr/bin/env python3%g" /usr/local/bin/meson
      sed -i "s%^#!/usr/bin/python3$%#!/usr/bin/env python3%g" $CRAFT_PART_INSTALL/usr/bin/meson
    build-packages:
      - python3-pip
      - libdbus-1-dev

  pipewire:
    plugin: meson
    after: [meson-deps]
    source: https://gitlab.freedesktop.org/pipewire/pipewire.git
    source-tag: '0.3.66'
    meson-parameters:
      - --prefix=/usr
      - -Doptimization=3
      - -Ddebug=true
      - -Dexamples=disabled
      - -Dman=disabled
      - -Dtests=disabled
      - -Dsystemd=enabled
      - -Dsnap=enabled
    build-packages:
      - libsdl2-dev
      - libreadline-dev
      - libncursesw5-dev
      - libsndfile1-dev
      - libpulse-dev
      - libusb-1.0-0-dev
      - libsystemd-dev
      - libapparmor-dev
      - libsnapd-glib-dev
      - libbluetooth-dev
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/patches/add-snap-support.diff
    stage-packages:
      - libgsound0
      - libcanberra-pulse
      - libsnapd-glib1
      - libbluetooth3
      - psmisc

  conditioning:
    plugin: nil
    after: [pipewire]
    override-prime: |
      mkdir -p snap/command-chain
      cp -a $CRAFT_PROJECT_DIR/scripts/* snap/command-chain/
      craftctl default
